// Derives src/dark.css from the light stylesheets so dark mode follows every
// later style change. Usage: node scripts/dark-theme.mjs [--check]
// --check exits non-zero when src/dark.css is out of date.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const sources = ["src/style.css", "src/features.css", "src/task-history.css", "src/v3.css", "src/v4.css"];
const output = "src/dark.css";
// The terminal and the screen overlay are dark in both themes.
const keepSelector = /\bterm\b|overlay|\.border-window/;
const colorProps = /^(--[\w-]+|color|background|background-color|border|border-(top|right|bottom|left)(-color)?|border-color|outline|outline-color|fill|stroke|caret-color|accent-color|text-decoration-color)$/;
const hexColor = /#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})\b/g;
const hasHex = /#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})\b/;

function parseHex(hex) {
  let h = hex.slice(1);
  if (h.length <= 4) h = [...h].map((c) => c + c).join("");
  const n = (i) => parseInt(h.slice(i, i + 2), 16) / 255;
  return { r: n(0), g: n(2), b: n(4), a: h.length === 8 ? n(6) : 1 };
}
function toHsl({ r, g, b }) {
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return { h: 0, s: 0, l };
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  const h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return { h: h / 6, s, l };
}
function fromHsl({ h, s, l }) {
  const f = (n) => {
    const k = (n + h * 12) % 12;
    const a = s * Math.min(l, 1 - l);
    return Math.round(255 * (l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1))));
  };
  return `#${[f(0), f(8), f(4)].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
}
export function darken(hex, fill = false) {
  const rgba = parseHex(hex);
  // Translucent shadows and scrims already work on dark surfaces.
  if (rgba.a < 1) return hex;
  const c = toHsl(rgba);
  // Vivid fills (status dots, danger buttons) keep their colour and contrast.
  if (fill && c.s >= 0.15 && c.l < 0.8) return hex;
  if (c.s < 0.15) {
    // Surfaces keep their order (cards stay lighter than the page); borders
    // and text invert so they stay visible on those surfaces.
    const l = c.l >= 0.93 ? 0.12 + (c.l - 0.93) * 0.8 : 0.2 + (0.93 - c.l) * 0.85;
    return fromHsl({ ...c, s: c.s * 0.3, l: Math.min(l, 0.93) });
  }
  if (c.l > 0.8) return fromHsl({ h: c.h, s: Math.min(c.s, 0.4), l: 0.17 + (1 - c.l) * 0.6 });
  if (c.l < 0.45) return fromHsl({ ...c, l: 0.66 + (0.45 - c.l) * 0.3 });
  return fromHsl({ ...c, l: Math.max(c.l, 0.58) });
}
const saturatedFill = (value) =>
  [...value.matchAll(hexColor)].some(([hex]) => {
    const c = toHsl(parseHex(hex));
    return c.s >= 0.15 && c.l > 0.25 && c.l < 0.75;
  });

function rules(css) {
  // Minimal parser for flat rules and one level of @media/@supports nesting.
  const out = [];
  css = css.replace(/\/\*[\s\S]*?\*\//g, "");
  let i = 0;
  const block = (text, wrapper) => {
    let j = 0;
    while (j < text.length) {
      const open = text.indexOf("{", j);
      if (open < 0) break;
      const selector = text.slice(j, open).trim();
      if (selector.startsWith("@")) {
        let depth = 1, k = open + 1;
        while (depth && k < text.length) depth += text[k] === "{" ? 1 : text[k] === "}" ? -1 : 0, k++;
        if (/^@(media|supports)/.test(selector)) block(text.slice(open + 1, k - 1), selector);
        j = k;
        continue;
      }
      const close = text.indexOf("}", open);
      out.push({ wrapper, selector, body: text.slice(open + 1, close) });
      j = close + 1;
    }
  };
  block(css, null);
  return out;
}

export function build() {
  const lines = [
    "/* Generated by scripts/dark-theme.mjs from the light stylesheets. Do not edit. */",
    "@media (prefers-color-scheme: dark) {",
  ];
  for (const file of sources) {
    for (const { wrapper, selector, body } of rules(readFileSync(path.join(root, file), "utf8"))) {
      if (keepSelector.test(selector) || (wrapper && !/^@media/.test(wrapper))) continue;
      const decls = body.split(";").map((d) => d.trim()).filter(Boolean).map((d) => {
        const at = d.indexOf(":");
        return [d.slice(0, at).trim(), d.slice(at + 1).trim()];
      });
      const filled = decls.some(([p, v]) => /^background/.test(p) && saturatedFill(v));
      const changed = decls
        .filter(([p, v]) => colorProps.test(p) && hasHex.test(v) && !(p === "color" && filled))
        .map(([p, v]) => [p, v.replace(hexColor, (hex) => darken(hex, /^background/.test(p)))]);
      if (!changed.length) continue;
      const rule = `  ${selector.replace(/\s+/g, " ")} { ${changed.map(([p, v]) => `${p}: ${v};`).join(" ")} }`;
      lines.push(wrapper ? `  ${wrapper} {\n  ${rule}\n  }` : rule);
    }
  }
  lines.push("}", "");
  return lines.join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = build();
  const target = path.join(root, output);
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {}
    if (current !== next) {
      console.error(`${output} is out of date; run node scripts/dark-theme.mjs`);
      process.exit(1);
    }
  } else {
    writeFileSync(target, next);
  }
}
