export type Metrics = {
  schema_version: number;
  origin: string;
  wall_ms: number;
  complete: boolean;
  phases: { name: string; wall_ms: number; count: number; max_ms: number }[];
  bytes: Record<string, number | string>;
  files: Record<string, number | string>;
  samples: { offset_ms: number; payload_bytes: number | string }[];
  outputs: { name: string; bytes: number | string | null; status: string }[];
  project_id?: string | null;
  project_name?: string | null;
  remote_job_id?: string | null;
  first_payload_offset_ms?: number | null;
  last_payload_offset_ms?: number | null;
  rtt_ms?: number | null;
  transport?: string | null;
  direction?: string | null;
  parent_task_id?: string | null;
  dimensions?: Record<string, string>;
};
export type Task = {
  metrics?: Metrics;
  server_metrics?: Metrics;
  connection_id?: string;
  connection_name?: string;
  task_id: string;
  kind: string;
  status: string;
  arguments: Record<string, any>;
  started_at: number;
  ended_at?: number;
  result?: { exit_code?: number };
  error?: { message: string; code?: string };
  output_tail?: string;
  approval_deadline?: number;
  desktop_tier?: DesktopTier;
  approved_by_rule?: string;
  progress?: { received: number; total: number; bytes: number };
};
export type DesktopTier = "observe" | "control" | "high";
export type TierPolicy = "allow" | "confirm" | "deny";
export type AllowRule = {
  id: string;
  kind: string;
  scope: "similar" | "session";
  program?: string | null;
  cwd?: string | null;
  server?: string | null;
  tool?: string | null;
  tier?: DesktopTier | null;
  created_at: number;
  expires_at?: number | null;
};
export type SavedConnection = {
  id: string;
  name: string;
  server: string;
  cert: string;
  token_file: string;
  keychain_account?: string;
  certificate_fingerprint?: string;
};
export type Settings = {
  connections?: SavedConnection[];
  server: string;
  cert: string;
  token_file: string;
  backend_config: string;
  keychain_account?: string;
  certificate_fingerprint?: string;
};
export type Snapshot = {
  connections?: {
    id: string;
    name: string;
    connection: Snapshot["connection"];
    policy: Snapshot["policy"];
  }[];
  today_summary: Record<string, number>;
  safety: {
    restrict_paths: boolean;
    roots: string[];
    approval: string;
    retention_days: number;
    yield_until: number;
    desktop?: Record<DesktopTier, TierPolicy>;
  };
  allow_rules?: AllowRule[];
  workspaces: {
    connection_id?: string;
    connection_name?: string;
    root: string;
    time: number;
    status: string;
    error?: { message: string };
  }[];
  policy: { paused: boolean; desktop_enabled: boolean };
  tasks: Task[];
  total_tasks: number;
  active_count: number;
  backends: {
    name: string;
    display_name?: string;
    backend_name?: string;
    connection_id?: string;
    state: string;
    session?: string;
    command: string;
    tool_count?: number;
    tiers?: Record<string, DesktopTier> | null;
  }[];
  version: string;
  protocol: number;
  connection: {
    state: string;
    server: string;
    since: number;
    rtt_ms?: number;
    error?: string;
  };
};
export type AppState = {
  preferences: {
    show_overlay: boolean;
    yield_input: boolean;
    notifications: boolean;
    keep_awake: boolean;
    auto_connect: boolean;
  };
  worker_running: boolean;
  worker_starting?: boolean;
  snapshot: Snapshot | null;
  settings: Settings;
  data_dir: string;
  legacy_running: boolean;
  legacy_detected?: boolean;
  autostart: boolean;
  platform: string;
};
